import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import type { StockNews, StockProject, StockSnapshot } from "./types.ts";
import { validateStockSnapshot } from "./stocks.ts";

const contentDir=new URL("../content/",import.meta.url),currentUrl=new URL("stocks.json",contentDir),historyDir=new URL("stocks-history/",contentDir);
const now=new Date(),generatedAt=now.toISOString(),date=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(now),userAgent="free-ai-directory-stocks/1.0 (+https://www.qaz5678.xyz/methodology/)";
const aiPattern=/\b(ai|artificial intelligence|llm|gpt|machine learning|agent|agents|neural|reinforcement learning)\b/i,stockPattern=/\b(stock|stocks|equity|equities|trading|trader|invest|investment|portfolio|market|quant|finance|financial|earnings|fund|asset|hedge fund|wall street|broker|securities|shorting|bull|bear|sentiment)\b/i;
type Candidate={platform:string;title:string;url:string;evidenceUrl:string;source:string;publishedAt:string;signal:number;context:string;sourceScore?:number};
type Repo={id:string;name:string;kind:StockProject["kind"];category:StockProject["category"];summary:string};
const repos:Repo[]=[
  {id:"TauricResearch/TradingAgents",name:"TradingAgents",kind:"工具",category:"多 Agent",summary:"多个专业 Agent 协作完成市场、基本面、新闻、观点辩论与风险分析。"},
  {id:"hsliuping/TradingAgents-CN",name:"TradingAgents-CN",kind:"工具",category:"多 Agent",summary:"面向中文用户和 A 股、港股、美股场景适配的多 Agent 金融分析框架。"},
  {id:"TraderAlice/OpenAlice",name:"OpenAlice",kind:"工具",category:"交易工作台",summary:"覆盖股票、商品、外汇和宏观研究流程的本地 AI 交易 Agent 工作台。"},
  {id:"ValueCell-ai/valuecell",name:"ValueCell",kind:"工具",category:"股票研究",summary:"社区驱动的多 Agent 金融应用平台，覆盖股票研究、跟踪与策略分析。"},
  {id:"HKUDS/Vibe-Trading",name:"Vibe-Trading",kind:"工具",category:"交易工作台",summary:"把金融问题转成可运行分析任务的开源个人交易 Agent 研究工作台。"},
  {id:"TradingGoose/TradingGoose.github.io",name:"TradingGoose",kind:"工具",category:"多 Agent",summary:"基于事件驱动研究和多 Agent 协作的股票分析与组合管理平台。"},
  {id:"AI4Finance-Foundation/FinGPT",name:"FinGPT",kind:"开源项目",category:"股票研究",summary:"面向金融领域的大语言模型、数据与应用研究项目。"},
  {id:"AI4Finance-Foundation/FinRL",name:"FinRL",kind:"开源项目",category:"量化框架",summary:"用于金融强化学习研究、训练、回测与实验的开源框架。"},
  {id:"microsoft/qlib",name:"Qlib",kind:"开源项目",category:"量化框架",summary:"微软开源的 AI 量化投资研究平台，覆盖数据、模型、策略与回测流程。"},
  {id:"AI4Finance-Foundation/FinRobot",name:"FinRobot",kind:"开源项目",category:"多 Agent",summary:"将大模型、量化分析和 Agent 工作流用于金融研究的开源平台。"},
  {id:"Chen-zexi/LangAlpha",name:"LangAlpha",kind:"开源项目",category:"股票研究",summary:"面向股票市场研究的多 Agent 金融分析工作流。"},
  {id:"gsaini/financial-research-analyst-agent",name:"Financial Research Analyst Agent",kind:"开源项目",category:"股票研究",summary:"协调多个专业 Agent、数据源和回测模块的股票研究系统。"}
];

const clean=(value:string)=>value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g," ").trim();
const round=(value:number)=>Math.round(value*10)/10,hash=(value:string)=>createHash("sha1").update(value).digest("hex").slice(0,16),host=(url:string)=>{try{return new URL(url).hostname.replace(/^www\./,"")}catch{return"unknown"}};
async function requestBody<T>(url:string,parse:(response:Response)=>Promise<T>,accept="application/json,text/html;q=0.9,application/xml;q=0.8",timeoutMs=25_000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs),agent=url.includes("nasdaq.com")?"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126 Safari/537.36":userAgent;try{const response=await fetch(url,{headers:{"user-agent":agent,accept},signal:controller.signal,redirect:"follow"});if(!response.ok)throw new Error(`${new URL(url).host} HTTP ${response.status}`);return await parse(response)}finally{clearTimeout(timer)}}
const text=(url:string,accept?:string,timeoutMs?:number)=>requestBody(url,response=>response.text(),accept,timeoutMs),json=<T>(url:string)=>requestBody(url,response=>response.json() as Promise<T>);
async function mapLimit<T,R>(items:T[],limit:number,worker:(item:T)=>Promise<R>){const results:R[]=new Array(items.length);let next=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(next<items.length){const index=next++;results[index]=await worker(items[index]!)} }));return results}
function tag(item:string,name:string){return clean(item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,"i"))?.[1]||"")}
function canonical(value:string){try{const url=new URL(value.replace(/^http:/,"https:"));for(const key of ["utm_source","utm_medium","utm_campaign","utm_content","utm_term","ref"])url.searchParams.delete(key);url.hash="";return url.toString().replace(/\/$/,"")}catch{return value}}
function titleKey(value:string){return clean(value).toLowerCase().replace(/\s[-–—|:]\s[^-–—|:]{2,35}$/," ").replace(/[^a-z0-9\u4e00-\u9fff]+/g," ").split(" ").filter(word=>word.length>1&&!new Set(["the","and","for","with","from","that","this","how","why","into","using"]).has(word)).slice(0,14).join(" ")}
function eligible(title:string,context:string,mode:"strict"|"ai-finance-feed"="strict"){if(!title)return false;if(mode==="ai-finance-feed")return stockPattern.test(title)&&aiPattern.test(`${title} ${context}`);return aiPattern.test(title)&&stockPattern.test(title)}
function newsSignal(textValue:string):StockNews["signal"]{if(/\b(sec|finra|regulat|fraud|scam|risk|ban|law|compliance)\b/i.test(textValue))return"监管 / 风险";if(/\b(tool|platform|app|launch|agent|product|assistant)\b/i.test(textValue))return"工具 / 产品";if(/\b(research|model|strategy|backtest|predict|forecast|quant)\b/i.test(textValue))return"研究 / 策略";return"市场 / 公司"}

async function fetchProjects():Promise<StockProject[]>{
  const values=await mapLimit(repos,4,async repo=>{const url=`https://github.com/${repo.id}`,[page,feed]=await Promise.all([text(url),text(`${url}/commits.atom`,"application/atom+xml,application/xml;q=0.9")]);const stars=Number(page.match(/"stargazerCount":(\d+)/)?.[1]),forks=Number(page.match(/"forksCount":(\d+)/)?.[1]),updatedAt=tag(feed,"updated");if(!Number.isFinite(stars)||!Number.isFinite(forks)||!updatedAt)throw new Error(`${repo.id} 元数据不完整`);return{repo,stars,forks,updatedAt:new Date(updatedAt).toISOString()}}),maxStars=Math.max(...values.map(item=>Math.log1p(item.stars))),maxForks=Math.max(...values.map(item=>Math.log1p(item.forks)));
  return values.map(({repo,stars,forks,updatedAt})=>{const popularityScore=round((Math.log1p(stars)/maxStars*80)+(Math.log1p(forks)/maxForks*20)),ageDays=Math.max(0,(Date.now()-new Date(updatedAt).getTime())/86400_000),freshnessScore=round(100*Math.pow(.5,ageDays/120)),score=round(popularityScore*.65+freshnessScore*.35),url=`https://github.com/${repo.id}`;return{id:repo.id.toLowerCase(),name:repo.name,kind:repo.kind,category:repo.category,summary:repo.summary,url,sourceUrl:url,stars,forks,updatedAt,popularityScore,freshnessScore,score}}).sort((a,b)=>b.score-a.score||b.stars-a.stars);
}
async function fetchHn():Promise<Candidate[]>{const terms=["AI stock trading","AI investing","LLM finance","AI portfolio","AI quantitative trading","AI financial analysis"],since=Math.floor((Date.now()-90*86400_000)/1000),pages=await mapLimit(terms,3,async query=>{try{const params=new URLSearchParams({query,tags:"story",numericFilters:`created_at_i>${since}`,hitsPerPage:"100"});return(await json<{hits?:any[]}>(`https://hn.algolia.com/api/v1/search_by_date?${params}`)).hits||[]}catch{return[]}});return pages.flat().flatMap((row:any)=>{const title=clean(String(row.title||"")),context=clean(String(row.story_text||""));if(!eligible(title,context,"strict"))return[];const evidenceUrl=`https://news.ycombinator.com/item?id=${row.objectID}`,url=canonical(String(row.url||evidenceUrl));return[{platform:"Hacker News",title,url,evidenceUrl,source:host(url),publishedAt:new Date(row.created_at).toISOString(),signal:Number(row.points||0)+Number(row.num_comments||0)*1.6,context:`${title} ${context}`} ]})}
async function fetchRss(platform:string,url:string,mode:"strict"|"ai-finance-feed"="strict",timeoutMs=25_000):Promise<Candidate[]>{const xml=await text(url,"application/rss+xml,application/xml;q=0.9",timeoutMs),items=xml.match(/<item>[\s\S]*?<\/item>/gi)||[];return items.flatMap((item,index)=>{const title=tag(item,"title"),description=tag(item,"description"),destination=canonical(tag(item,"link")),published=tag(item,"pubDate");if(!eligible(title,description,mode)||!destination.startsWith("https://")||!published)return[];return[{platform,title,url:destination,evidenceUrl:destination,source:platform,publishedAt:new Date(published).toISOString(),signal:Math.max(1,100-index*4),context:`${title} ${description}`} ]})}
async function fetchDev():Promise<Candidate[]>{const tags=["ai","fintech","machinelearning","algorithmictrading","investing"],pages=await mapLimit(tags,3,tagName=>fetchRss("DEV Community",`https://dev.to/feed/tag/${tagName}`,"strict"));return pages.flat()}
function fuseNews(candidates:Candidate[]):StockNews[]{const unique=new Map<string,Candidate>();for(const item of candidates){const key=`${item.platform}:${canonical(item.url).toLowerCase()}`,old=unique.get(key);if(!old||item.signal>old.signal)unique.set(key,item)}const rows=[...unique.values()];for(const platform of new Set(rows.map(item=>item.platform))){const group=rows.filter(item=>item.platform===platform).sort((a,b)=>a.signal-b.signal);group.forEach((item,index)=>item.sourceScore=round(group.length<2?50:index/(group.length-1)*100))}const groups=new Map<string,Candidate[]>();for(const item of rows){const key=titleKey(item.title)||canonical(item.url).toLowerCase(),group=groups.get(key)||[];group.push(item);groups.set(key,group)}const ranked=[...groups.values()].map(group=>{const latest=group.reduce((a,b)=>new Date(a.publishedAt)>new Date(b.publishedAt)?a:b),evidence=[...new Map(group.map(item=>[`${item.platform}:${item.evidenceUrl}`,item])).values()].sort((a,b)=>(b.sourceScore||0)-(a.sourceScore||0)),sourcePlatforms=[...new Set(evidence.map(item=>item.platform))],sourceScore=round(evidence.slice(0,2).reduce((sum,item)=>sum+(item.sourceScore||0),0)/Math.min(2,evidence.length)),ageDays=Math.max(0,(Date.now()-new Date(latest.publishedAt).getTime())/86400_000),freshnessScore=round(100*Math.pow(.5,ageDays/14)),score=round(sourceScore*.50+freshnessScore*.40+Math.min(10,(sourcePlatforms.length-1)*5));return{id:hash(canonical(latest.url).toLowerCase()),title:latest.title,url:latest.url,publishedAt:latest.publishedAt,source:latest.source,sourcePlatforms,evidence:evidence.map(item=>({platform:item.platform,url:item.evidenceUrl})),signal:newsSignal(group.map(item=>item.context).join(" ")),sourceScore,freshnessScore,score}}).sort((a,b)=>b.score-a.score||new Date(b.publishedAt).getTime()-new Date(a.publishedAt).getTime()),selected:StockNews[]=[],counts=new Map<string,number>();for(const item of ranked){const primary=item.sourcePlatforms[0]!;if((counts.get(primary)||0)>=8)continue;selected.push(item);counts.set(primary,(counts.get(primary)||0)+1);if(selected.length===12)break}for(const item of ranked){if(selected.length===12)break;if(!selected.includes(item))selected.push(item)}return selected}

async function previousSnapshot():Promise<StockSnapshot|null>{try{const data=JSON.parse(await readFile(currentUrl,"utf8"));validateStockSnapshot(data);return data}catch{return null}}
const previous=await previousSnapshot(),sourceStatus:StockSnapshot["sourceStatus"]=[];
let projects:StockProject[];try{projects=await fetchProjects();if(projects.length!==12)throw new Error(`只得到 ${projects.length} 个项目`);sourceStatus.push({name:"GitHub 项目元数据",url:"https://github.com/",ok:true,note:"12 个项目的 Star、Fork 与最近提交已更新"})}catch(error){if(!previous?.projects.length)throw error;projects=previous.projects;sourceStatus.push({name:"GitHub 项目元数据",url:"https://github.com/",ok:false,note:`更新失败，保留上一版：${error instanceof Error?error.message:String(error)}`})}
async function newsSource(name:string,url:string,run:()=>Promise<Candidate[]>){try{const rows=await run();if(rows.length<1)throw new Error("没有符合条件的条目");sourceStatus.push({name,url,ok:true,note:`抓取 ${rows.length} 条候选`});return rows}catch(error){sourceStatus.push({name,url,ok:false,note:error instanceof Error?error.message:String(error)});return[]}}
const candidates=(await Promise.all([newsSource("Hacker News","https://hn.algolia.com/api",fetchHn),newsSource("DEV Community","https://dev.to/feed/tag/fintech",fetchDev),newsSource("Nasdaq AI","https://www.nasdaq.com/feed/rssoutbound?category=Artificial+Intelligence",()=>fetchRss("Nasdaq AI","https://www.nasdaq.com/feed/rssoutbound?category=Artificial+Intelligence","ai-finance-feed")),newsSource("MarketWatch","https://feeds.content.dowjones.io/public/rss/mw_topstories",()=>fetchRss("MarketWatch","https://feeds.content.dowjones.io/public/rss/mw_topstories","strict")),newsSource("SEC","https://www.sec.gov/news/pressreleases.rss",()=>fetchRss("SEC","https://www.sec.gov/news/pressreleases.rss","strict"))])).flat();let news=fuseNews(candidates);const successful=sourceStatus.filter(item=>item.ok&&item.name!=="GitHub 项目元数据");if(successful.length<2||news.length!==12){if(!previous?.news.length)throw new Error(`AI 炒股多源新闻不足：${news.length} 条，成功来源 ${successful.length} 个`);news=previous.news;sourceStatus.push({name:"AI 炒股新闻融合榜",url:"https://www.qaz5678.xyz/methodology/",ok:false,note:"来源少于 2 个或条目不足，保留上一版"})}else sourceStatus.push({name:"AI 炒股新闻融合榜",url:"https://www.qaz5678.xyz/methodology/",ok:true,note:`${successful.map(item=>item.name).join(" + ")} 归一化后按 50% 来源热度、40% 时效、10% 跨源覆盖排序`});
const snapshot:StockSnapshot={schemaVersion:1,date,generatedAt,timezone:"Asia/Shanghai",projects,news,sourceStatus};validateStockSnapshot(snapshot);await mkdir(historyDir,{recursive:true});const tempUrl=new URL(`stocks.${process.pid}.tmp`,contentDir);await writeFile(tempUrl,JSON.stringify(snapshot,null,2)+"\n");await rename(tempUrl,currentUrl);await writeFile(new URL(`${date}.json`,historyDir),JSON.stringify(snapshot,null,2)+"\n");console.log(`AI 炒股情报更新完成：${date}，项目 ${projects.length}、新闻 ${news.length}`);for(const source of sourceStatus)console.log(`${source.ok?"OK":"STALE"} ${source.name}: ${source.note}`);
